#pragma kernel CSMain
#include "Utils.cginc"

int screenWidth;
int screenHeight;
StructuredBuffer<uint> frameIndex;
StructuredBuffer<uint3> currentFrameBuffer;
RWTexture2D<float4> accumulationTexture;

[numthreads(32,32,1)]
void CSMain (uint3 id : SV_DispatchThreadID)
{
    if (id.x >= (uint) screenWidth || id.y >= (uint) screenHeight)
    {
        return;
    }

    float3 currentColor = (float3)currentFrameBuffer[getLinearPixelIndex(id.xy, screenWidth)] / COLOR_SCALE;
    float alpha = rcp(frameIndex[0] + 1.0);
    // TODO: Double check that we are accumulating in the correct color space
    float4 accumulatedColor = accumulationTexture[id.xy];

    accumulationTexture[id.xy] = lerp(accumulatedColor, float4(currentColor,1), alpha);
}