// Each #kernel tells which function to compile; you can have many kernels
#pragma kernel CSMain

#define T_MIN 0.1

StructuredBuffer<PathPayload> paths;
StructuredBuffer<uint> pathsContinueCounter;
StructuredBuffer<uint> pathsContinueCounterValue;
RWStructuredBuffer<uint> pathsContinueTmpCounter;
RWStructuredBuffer<PathHitRecord> pathHitRecords;
int gaussianCount;
RWStructuredBuffer<Gaussian3D> gaussiansBuffer;
RWStructuredBuffer<Gaussian3D> colorAccumulation;


// TODO: I think this is the equivalent of the opacity function but I need to research that
float opacityAtPoint(float4 pos, Gaussian gauss){
    float4x1 x = float4(gauss.pos.x, gauss.pos.y, gauss.pos.z, 1) - pos;
    x = abs(x);
                
    float4 intermediateX = mul(gauss.invCov, x);
    float exponent = -0.5 * mul(transpose(x), intermediateX);
    float g = pow(EULER_NUM, exponent);

    return g;
}


[numthreads(128,1,1)]
void CSMain (uint3 id : SV_DispatchThreadID)
{
    if (id.x > pathsContinueCounterValue[0])
    {
        return;
    }

    PathPayload path = paths[id.x];

    float transmittance = 1;
    float color = 0;

    // TODO: Check for intersections with Gaussians' BVH 
    for(int i =0; i < gaussianCount; i++){
        // Find intersection point 
        // a, b, and c are just temporary variables to break up the calculation.
        float4x1 a = transpose(gaussiansBuffer[i].pos - path.origin);
        float4 b = gaussiansBuffer[i].cov * path.direction;
        float tjNumerator = a * b;
        float4x1 c = transpose(path.direction)
        float tjDenominator = c * b;
        float tj = tjNumerator / tjDenominator;

        float4 rx = path.origin + (tj * path.direction);

        // TODO: I think this is the equivalent of the opacity function but I need to research that
        float contribution = opacityAtPoint(rx, gaussiansBuffer[i]);

        // TODO: Transmittance should change based on distance from the origin
        // If the transmittance is above the minimum and occurs before an intersection with a mesh
        if(transmittance > T_MIN && tj < t){
            color += contribution * gaussiansBuffer[i].color; 
        }





    }


}
