#pragma kernel CSMain

int screenWidth;
int screenHeight;
StructuredBuffer<uint> frameIndex;
Texture2D<float4> renderTexture;
RWTexture2D<float4> accumulationTexture;

[numthreads(32,32,1)]
void CSMain (uint3 id : SV_DispatchThreadID)
{
    if (id.x >= (uint) screenWidth || id.y >= (uint) screenHeight)
    {
        return;
    }

    // convert color from linear to sRGB color space
    float4 currentColor = renderTexture[id.xy];
    currentColor.rgb = pow(abs(currentColor.rgb), 1/2.2);

    float alpha = rcp(frameIndex[0] + 1.0);
    float4 accumulatedColor = accumulationTexture[id.xy];

    accumulationTexture[id.xy] = lerp(accumulatedColor, currentColor, alpha);
}