// Each #kernel tells which function to compile; you can have many kernels
#pragma kernel CSMain
#include "utils.cginc"

#define T_MIN 0.1

StructuredBuffer<PathPayload> paths;
StructuredBuffer<uint> pathsContinueCounter;
StructuredBuffer<uint> pathsContinueCounterValue;
RWStructuredBuffer<uint> pathsContinueTmpCounter;
RWStructuredBuffer<PathHitRecord> pathHitRecords;
RWStructuredBuffer<Gaussian> gaussiansBuffer;
RWTexture2D<float4> gaussianTexture;
int pathCount;
int gaussianCount;
int screenWidth;
int pathsPerPixel;

// src: Relightable 3D Gaussians Section 3.1, Equation 1 https://arxiv.org/pdf/2311.16043#page.4
float opacityAtPoint(float3 pos, Gaussian gauss){

    float4x1 gaussianCenterPosDiffMatrix = float4((gauss.pos - pos).xyz, 1);
    gaussianCenterPosDiffMatrix = abs(gaussianCenterPosDiffMatrix);
                
    float4 gaussianCenterPosDiffMatrixTimesInvCov = mul(gauss.invCov, gaussianCenterPosDiffMatrix);
    float exponent = -0.5 * mul(transpose(gaussianCenterPosDiffMatrix), gaussianCenterPosDiffMatrixTimesInvCov);
    float g = pow(EULER_NUM, exponent);

    return g;
}

[numthreads(128,1,1)]
void CSMain (uint3 id : SV_DispatchThreadID)
{
    if (id.x > (uint) pathCount)
    {
        return;
    }

    uint2 pixelIndex = getPixelIndex(id.x, pathsPerPixel, screenWidth);
    PathPayload path = paths[id.x];

    float transmittance = 1;
    float4 color = 0;

    // TODO: Check for intersections with Gaussians' BVH 
    for(int i =0; i < gaussianCount; i++){
        // Find intersection point 
        // a, b, and c are just temporary variables to break up the calculation.

        // src: Relightable 3D Gaussians section 4.1, equation 14 https://arxiv.org/pdf/2311.16043#page.9
    
        // Values for numerator and denominator 
        float4 pathDirectionVec4 = float4(path.direction.xyz, 1);
        float4x1 pathDirectionMatrix = pathDirectionVec4;
        float4x1 covTimesDirection = mul(gaussiansBuffer[i].cov, pathDirectionVec4);

        // Numerator Calc
        float4x1 bufferOriginDif = float4((gaussiansBuffer[i].pos - path.origin).xyz, 1);
        float1x4 bufferOriginDifTranspose = transpose(bufferOriginDif);
        float tjNumerator = mul(bufferOriginDifTranspose, covTimesDirection);

        // Denominator Calc
        float1x4 pathDirectionMatrixTranspose = transpose(pathDirectionMatrix);
        float tjDenominator = mul(pathDirectionMatrixTranspose, covTimesDirection);

        // Division
        float tj = tjNumerator / tjDenominator;

        // rx is the point where this Gaussian has maximum influence on this Gaussian
        float3 rx = path.origin + (tj * float3(path.direction.xyz));

        // TODO: I think this is the equivalent of the opacity function but I need to research that
        float contribution = opacityAtPoint(rx, gaussiansBuffer[i]);

        // TODO: Ray should accumlate color as it moves through the Gaussian
        // TODO: Transmittance should change based on distance other gaussians between it and the origin
        // If the transmittance is above the minimum and occurs before an intersection with a mesh
        if(transmittance > T_MIN /*&& tj < pathHitRecords[id.x].t*/)
        {
           color += contribution * gaussiansBuffer[i].color;
        }
    }

    gaussianTexture[pixelIndex] = color;
}