#pragma kernel CSMain
#include "Utils.cginc"

int pathCount;
int pathsPerPixel;
int screenWidth;
float invScreenHeight;
float tanFovHalf;
StructuredBuffer<CameraData> cameraData;
RWStructuredBuffer<PathPayload> paths; 
RWStructuredBuffer<uint> pathsContinueCounter;

[numthreads(128,1,1)]
void CSMain (uint3 id : SV_DispatchThreadID)
{
    if (id.x > (uint) pathCount)
    {
        return;
    }

    uint pathId = id.x;
    uint2 pixelIndex = getPixelIndex(pathId, pathsPerPixel, screenWidth);
    float pixelDirXCamSpace = ((2 * pixelIndex.x + 1) * invScreenHeight - screenWidth * invScreenHeight) * tanFovHalf;
    float pixelDirYCamSpace = ((2 * pixelIndex.y + 1) * invScreenHeight - 1) * tanFovHalf;

    // camera's image plane is at z = 1
    float3 pixelDirCamSpace = float3(pixelDirXCamSpace, pixelDirYCamSpace, 1);

    // direction vectors are uneffected by translations
    float3x3 cameraToWorld = quatToRotMatrix(cameraData[0].quaternion);
    float3 pixelDirWorldSpace = normalize(mul(cameraToWorld, pixelDirCamSpace));
    paths[pathId].direction = float4(pixelDirWorldSpace, 0);
    paths[pathId].origin = cameraData[0].position;
    paths[pathId].throughput = float4(1,1,1,1);

    uint prevIndex = pathsContinueCounter.IncrementCounter();
    pathsContinueCounter[prevIndex] = pathId;
}