#pragma kernel CSMain
#include "utils.cginc"

RWStructuredBuffer<PathPayload> paths;
StructuredBuffer<uint> pathsEndCounter;
RWStructuredBuffer<uint> pathsContinueCounter;
StructuredBuffer<CameraParams> cameraParamsConst;

[numthreads(32,1,1)]
void CSMain (uint3 id : SV_DispatchThreadID)
{
    if (id.x > pathsEndCounter[cameraParamsConst[0].pathCount])
    {
        return;
    }

    int x = (id.x / cameraParamsConst[0].pathsPerPixel) % cameraParamsConst[0].screenWidth;
    int y = (id.x / cameraParamsConst[0].pathsPerPixel) / cameraParamsConst[0].screenWidth;
    float pixelDirXCamSpace = ((2 * x + 1) * cameraParamsConst[0].invScreenHeight - cameraParamsConst[0].screenWidth * cameraParamsConst[0].invScreenHeight) * cameraParamsConst[0].tanFovHalf;
    float pixelDirYCamSpace = ((-2 * y - 1) * cameraParamsConst[0].invScreenHeight + 1) * cameraParamsConst[0].tanFovHalf;

    // camera's image plane is at z = 1
    float3 pixelDirCamSpace = float3(pixelDirXCamSpace, pixelDirYCamSpace, 1);

    // direction vectors are uneffected by translations
    float3x3 cameraToWorld = quatToRotMatrix(cameraParamsConst[0].quaternion);
    float3 pixelDirWorldSpace = mul(cameraToWorld, pixelDirCamSpace);

    uint pathId = pathsEndCounter[id.x];
    paths[pathId].direction = float4(pixelDirWorldSpace,0);

    uint prevIndex = pathsContinueCounter.IncrementCounter();
    pathsContinueCounter[prevIndex] = pathId;
}