#pragma kernel CSMain
#include "utils.cginc"

StructuredBuffer<PathPayload> paths;
StructuredBuffer<uint> pathsContinueCounter;
StructuredBuffer<uint> pathsContinueCounterValue;
StructuredBuffer<GameObjectData> gameObjectDatas;
int gameObjectDataCount;
StructuredBuffer<AABB> aabbs;
StructuredBuffer<Triangle> triangles;
StructuredBuffer<Vertex> vertices;
StructuredBuffer<MaterialData> materialDatas;
Texture2DArray<float4> textures;
SamplerState samplertextures;
RWStructuredBuffer<PathHitRecord> pathHitRecords;
RWStructuredBuffer<uint> pathsContinueTmpCounter;

[numthreads(128,1,1)]
void CSMain (uint3 id : SV_DispatchThreadID)
{
    if (id.x > pathsContinueCounterValue[0])
    {
        return;
    }

    uint pathId = pathsContinueCounter[id.x];
    PathPayload path = paths[pathId];

    PathHitRecord closestHit = pathHitRecords[pathId];
    closestHit.t = FLT_MAX;

    for (int i = 0; i < gameObjectDataCount; i++)
    {
        GameObjectData currGameObj = gameObjectDatas[i];
        float3 pathOriginObjSpace = mul(currGameObj.worldToObject, float4(path.origin,1)).xyz;
        float3 pathDirObjSpace = mul(currGameObj.worldToObject, path.direction).xyz;

        AABB aabb = aabbs[currGameObj.aabbRootIndex];
        // TODO: check for AABB intersections

        // ray-triangle intersection https://www.scratchapixel.com/lessons/3d-basic-rendering/ray-tracing-rendering-a-triangle/moller-trumbore-ray-triangle-intersection.html
        for (uint j = 0; j < aabb.triangleCount; j++)
        {
            Triangle tri = triangles[aabb.triangleStartIndex + j];
            float3 aToB = vertices[tri.v1].position - vertices[tri.v0].position;
            float3 aToC = vertices[tri.v2].position - vertices[tri.v0].position;
            float3 p = cross(pathDirObjSpace, aToC);

            float det  = dot(p, aToB);
            if (det < EPSILON)
            {
                continue;
            }

            float invDet = rcp(det);

            float3 aToOrigin = pathOriginObjSpace - vertices[tri.v0].position;
            float u = dot(p, aToOrigin) * invDet;
            if (u < 0 || u > 1)
            {
                continue; 
            }

            float3 q = cross(aToOrigin, aToB);
            float v = dot(q, pathDirObjSpace) * invDet;
            if (v < 0 || u + v > 1)
            {
                continue;
            }

            float t = dot(q, aToC) * invDet;

            if (t < closestHit.t && t > 0)
            {
                closestHit.t = t;

                MaterialData mat = materialDatas[currGameObj.materialIndex];
                closestHit.materialType = mat.type;

                float w = 1 - u - v;
                if (mat.type != MATERIAL_TEXTURED)
                {
                    closestHit.albedo = mat.albedo;
                }
                else
                {
                    float2 albedoUV = vertices[tri.v0].albedoUV * w + vertices[tri.v1].albedoUV * u + vertices[tri.v2].albedoUV * v;
                    closestHit.albedo = textures.SampleLevel(samplertextures, float3(albedoUV, mat.albedoTextureIndex), 0) * mat.albedo;
                }

                // float4 normal = mul(currGameObj.normalMatrix, float4(cross(aToB, aToC), 0));
                // normal.w = 0;
                // closestHit.normal = normalize(normal);
                float4 normal = mul(currGameObj.normalMatrix, float4(vertices[tri.v0].normal * w + vertices[tri.v1].normal * u + vertices[tri.v2].normal * v, 0));
                closestHit.normal = normalize(normal.xyz);
            }
        }
    }
   
    if (closestHit.t < FLT_MAX)
    {
        pathHitRecords[pathId] = closestHit;

        uint prevIndex = pathsContinueTmpCounter.IncrementCounter();
        pathsContinueTmpCounter[prevIndex] = pathId;
    }
}