#pragma kernel CSMain
#include "utils.cginc"

StructuredBuffer<PathPayload> paths;
StructuredBuffer<uint> pathsContinueCounter;
StructuredBuffer<CameraParams> cameraParamsConst;
int gameObjectDataCount;
StructuredBuffer<GameObjectData> gameObjectDatas;
StructuredBuffer<AABB> aabbs;
StructuredBuffer<Triangle> triangles;
RWStructuredBuffer<PathHitRecord> pathHitRecords;
RWStructuredBuffer<uint> pathsContinueTmpCounter;

[numthreads(32,1,1)]
void CSMain (uint3 id : SV_DispatchThreadID)
{
    if (id.x > pathsContinueCounter[cameraParamsConst[0].pathCount])
    {
        return;
    }

    uint pathId = pathsContinueCounter[id.x];
    PathPayload path = paths[pathId]; // hopefully a deep copy and not a reference

    PathHitRecord closestHit;
    closestHit.t = FLT_MAX;

    for (int i = 0; i < gameObjectDataCount; i++)
    {
        GameObjectData currGameObj = gameObjectDatas[i];
        float3 cameraPositionObjSpace = (float3) mul(currGameObj.worldToObject, float4(cameraParamsConst[0].position,1));
        float3 pathDirObjSpace = (float3) mul(currGameObj.worldToObject, path.direction);

        // TODO: check for AABB intersections
        AABB aabb = aabbs[currGameObj.aabbRootIndex];

        // Ray-triangle intersection source: https://www.scratchapixel.com/lessons/3d-basic-rendering/ray-tracing-rendering-a-triangle/moller-trumbore-ray-triangle-intersection.html
        for (uint j = 0; j < aabb.triangleCount; j++)
        {
            // TODO: precompute A,B,C,D potential perforamnce improvement (not always an improvement...)
            Triangle tri = triangles[aabb.triangleStartIndex + j];
            float3 aToB = (float3) (tri.positions[1] - tri.positions[0]);
            float3 aToC = (float3) (tri.positions[2] - tri.positions[0]);
            float3 p = cross(pathDirObjSpace, aToC);

            float det  = dot(p, aToB);
            if (det < EPSILON)
            {
                continue;
            }

            float invDet = 1 / det;

            float3 aToOrigin = cameraPositionObjSpace - (float3) tri.positions[0];
            float u = dot(p, aToOrigin) * invDet;
            if (u < 0 || u > 1)
            {
                continue; 
            }

            float3 q = cross(aToOrigin, aToB);
            float v = dot(q, pathDirObjSpace) * invDet;
            if (v < 0 || u + v > 1)
            {
                continue;
            }

            float t = dot(q, aToC) * invDet;

            if (t < closestHit.t)
            {
                closestHit.t = t;
                closestHit.u = u;
                closestHit.v = v;
                closestHit.materialIndex = currGameObj.materialIndex;
            }
        }
    }
    
    if (closestHit.t < FLT_MAX)
    {
        uint prevIndex = pathsContinueTmpCounter.IncrementCounter();
        pathsContinueTmpCounter[prevIndex] = pathId;
    }

    pathHitRecords[pathId] = closestHit;
}