#pragma kernel CSMain
#include "utils.cginc"

StructuredBuffer<uint> frameIndex;
StructuredBuffer<uint> pathsContinueTmpCounter;
StructuredBuffer<uint> pathsContinueTmpCounterValue;
StructuredBuffer<PathHitRecord> pathHitRecords;
StructuredBuffer<MaterialData> materialDatas;
int pathsPerPixel;
int screenWidth;
int pathBounceLimit;
RWStructuredBuffer<PathPayload> paths;
RWStructuredBuffer<uint> pathsContinueCounter;
RWTexture2D<float4> renderTexture;

[numthreads(128,1,1)]
void CSMain (uint3 id : SV_DispatchThreadID)
{
    if (id.x > pathsContinueTmpCounterValue[0])
    {
        return;
    }

    uint pathId = pathsContinueTmpCounter[id.x];
    PathHitRecord hitRecord = pathHitRecords[pathId];

    MaterialData materialData = materialDatas[hitRecord.materialIndex];
    uint2 pixelIndex = getPixelIndex(pathId, pathsPerPixel, screenWidth);

    float invPathsPerPixel = 1.0 / (pathsPerPixel - 1);
    renderTexture[pixelIndex] += paths[pathId].throughput * materialData.albedo * invPathsPerPixel;
    // TODO: I think the += is our issue here because the add is not immediate

    // if (materialData.type == 1) // emissive
    // {
    //     // write to texture
    //     float invPathsPerPixel = 1.0 / (pathsPerPixel - 1);
    //     renderTexture[pixelIndex] += paths[pathId].throughput * materialData.albedo * invPathsPerPixel;
    //     return;
    // }

    // if (paths[pathId].bounce >= (uint)pathBounceLimit)
    // {
    //     return;
    // }

    // // add normal offset to avoid collision with the same object
    // paths[pathId].origin += float3((hitRecord.t * paths[pathId].direction + hitRecord.normal * EPSILON).xyz);

    // // cosine weighted sample accounts for Lambert's Law, path continue count is the seed
    // int seed = getSeed(pathId, paths[pathId].bounce, frameIndex[0]);
    // float3 reflect = randCosHemisphereSample(hitRecord.normal.xyz, pixelIndex, seed);
    // paths[pathId].direction = float4(reflect, 0);
    // paths[pathId].bounce++;

    // // Lambertian Diffuse BRDF
    // paths[pathId].throughput *= materialData.albedo / PI;
   
    // // add path to continue
    // uint prevIndex = pathsContinueCounter.IncrementCounter();
    // pathsContinueCounter[prevIndex] = pathId;
}