#pragma kernel CSMain
#include "utils.cginc"

StructuredBuffer<uint> pathsContinueTmpCounter;
StructuredBuffer<uint> pathsContinueTmpCounterValue;
StructuredBuffer<PathHitRecord> pathHitRecords;
StructuredBuffer<MaterialData> materialDatas;
int pathsPerPixel;
int screenWidth;
int pathBounceLimit;
RWStructuredBuffer<PathPayload> paths;
// RWStructuredBuffer<uint> pathsContinueCounter;
RWTexture2D<float4> renderTexture;

[numthreads(32,1,1)]
void CSMain (uint3 id : SV_DispatchThreadID)
{
    if (id.x > pathsContinueTmpCounterValue[0])
    {
        return;
    }

    uint pathId = pathsContinueTmpCounter[id.x];
    PathHitRecord hitRecord = pathHitRecords[pathId];

    MaterialData materialData = materialDatas[hitRecord.materialIndex];
    if (materialData.type == 1) // emissive
    {
        // write to texture
        uint2 pixelIndex = getPixelIndex(pathId, pathsPerPixel, screenWidth);
        renderTexture[pixelIndex] = dot(paths[pathId].throughput, materialData.albedo);
        return;
    }

    if (paths[pathId].bounce >= (uint)pathBounceLimit)
    {
        return;
    }

    // Lambertain Diffuse

    // TODO: gen new dir

    // TODO: if bounce, new origin + bounce + add to continue
}