#pragma kernel CSMain
#include "Utils.cginc"

StructuredBuffer<uint> frameIndex;
StructuredBuffer<uint> pathsContinueTmpCounter;
StructuredBuffer<uint> pathsContinueTmpCounterValue;
StructuredBuffer<PathHitRecord> pathHitRecords;
int pathsPerPixel;
int screenWidth;
int pathBounce;
RWStructuredBuffer<PathPayload> paths;
RWStructuredBuffer<uint> pathsContinueCounter;
RWStructuredBuffer<uint3> currentFrameBuffer;

[numthreads(128,1,1)]
void CSMain (uint3 id : SV_DispatchThreadID)
{
    if (id.x > pathsContinueTmpCounterValue[0])
    {
        return;
    }

    uint pathId = pathsContinueTmpCounter[id.x];
    PathHitRecord hitRecord = pathHitRecords[pathId];

    uint2 pixelIndex = getPixelIndex(pathId, pathsPerPixel, screenWidth);

    if (hitRecord.materialType == MATERIAL_EMISSIVE)
    {
        uint idx = (pathId / pathsPerPixel);
        float invPathsPerPixel = 1.0 / pathsPerPixel;
        uint3 color = (uint3) (paths[pathId].throughput * hitRecord.albedo * invPathsPerPixel * COLOR_SCALE).xyz;

        InterlockedAdd(currentFrameBuffer[idx].x, color.x);
        InterlockedAdd(currentFrameBuffer[idx].y, color.y);
        InterlockedAdd(currentFrameBuffer[idx].z, color.z);

        return;
    }

    // add normal offset to avoid collision with itself
    paths[pathId].origin += hitRecord.t * paths[pathId].direction + float4(hitRecord.normal,0) * EPSILON;

    // cosine weighted sample accounts for Lambert's Law
    int seed = getSeed(pathBounce, frameIndex[0], pathId);
    float3 reflect = randCosHemisphereSample(hitRecord.normal, pixelIndex, seed);
    paths[pathId].direction = float4(reflect, 0);

    // Lambertian Diffuse BRDF
    paths[pathId].throughput *= hitRecord.albedo / PI;
   
    // add path to continue
    uint prevIndex = pathsContinueCounter.IncrementCounter();
    pathsContinueCounter[prevIndex] = pathId;
}